language: python
python:
  - "3.6"      # current default Python on Travis CI
git:
  depth: false  # To be able to find tags, otherwise it will fail
# command to install dependencies
install:
  - pip install codecov pytest pytest-cov sphinx
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - pytest --cov-report term --cov=auv_nav
  - sphinx-build -nWT -b dummy . _build/html
env:
- CODECOV_TOKEN=c86ba333-736f-4b14-bf54-44d0d363c338

after_success:
- codecov
