language: python
# Test python versions from 2016 onwards
python:
  - "3.6"
  - "3.7"
  - "3.8"
git:
  depth: false  # To be able to find tags, otherwise it will fail
# command to install dependencies
install:
  - pip install codecov pytest pytest-cov sphinx sphinx_rtd_theme recommonmark
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - pytest --cov-report term --cov=oplab --cov=auv_nav --cov=correct_images --cov=auv_cal
env:
- CODECOV_TOKEN=c86ba333-736f-4b14-bf54-44d0d363c338

after_success:
- codecov
